[workspace]
members = [
    "crates/lcrt-audio-pipewire",
    "crates/lcrt-core",
    "crates/lcrt-stt-whisper",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/hoangnguyen7474/lcrt"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_code = "forbid"
